#!/bin/bash
#The password for the next level is stored in a file called readme located in the home directory.
#Use this password to log into bandit1 using SSH. 
#Whenever you find a password for a level, use SSH (on port 2220) to log into that level and continue the game.

#User: bandit0
#password: bandit0

cat readme
#Final password: boJ9jbbUNNfktd78OOpsqOltutMc3MY1