#!/bin/bash

# The password for the next level is stored in a file called - located in the home directory
#user: bandit1
#password: boJ9jbbUNNfktd78OOpsqOltutMc3MY1

cat ./- 

#Final password: CV1DtqXWVFXTvM2F0k09SHz0YwRINYA9