#!/bin/bash

#The password for the next level is stored in a hidden file in the inhere directory.

#user: bandit3
#password: UmHadQclWmgdLOKQ3YNgjWxGoRMb5luK

ls -la
cd inhere
ls -la
cat .hidden 

#Final password: pIwrPrtPN36QITSp3EQaw936yaFoFgAB