#!/bin/bash

#The password for the next level is stored in a file somewhere under the 
#inhere directory and has all of the following properties:

# human-readable
# 1033 bytes in size
# not executable

#user: bandit5
#password: koReBOKuIDDepwhWk7jZC0RTdopnAYKh
cd inhere
find . -size 1033c ! -executable 
#./maybehere07/.file2
file ./maybehere07/.file2
#./maybehere07/.file2: ASCII text, with very long lines
cat ./maybehere07/.file2

#Final password: DXjZPULLxYr17uwoI01bNLQbtFemEgo7